SupercarMarket/supercarmarket.co.kr

.gitignore
package.json
src/components/common/button.stories.tsx
src/components/common/button.tsx
src/pages/index.tsx

pivot 커밋은 add button component랑 story 정도와 크로매틱 호스팅 추가 정도입니다. 이부분을 보시면 될 것 같습니다
이외에는 prettier를 추가하며 코드 스타일이 바뀐걸로인한 변동 내역입니다.
#1 
#2

feat: #2 Button Component and Story

---

src/components/layout/layout.tsx
src/constants/market.ts
src/utils/api/market.ts

- 마켓페이지 내 무한 리다이렉트가 발생
- 발생 원인
- 지난번 백엔드와의 엔드포인트 테스트 때, 리다이렉트 쿼리 변경에 미흡한 점이 있었습니다.
- 바꾸는김에 다른 페이지와 동일하게 클라이언트단 쿼리는 한글이 아닌 영어로 보일 수 있도록 수정하였습니다.
- `constants/market.ts` 내 `CATEGORY.value` 값 한글에서 영어로 변경
- `constants/market.ts` 내 `CATEGORY_MAPPING` 추가
- `utils/api/market.ts` 내 쿼리 변경 로직 추가
- #44

Hotfix: 마켓페이지 무한 리다이렉트 수정

---

src/components/fallback/error.tsx
src/components/fallback/index.ts
src/components/home/community/community.tsx
src/components/home/magazine/index.ts
src/components/home/magazine/magazine.tsx
src/components/home/market/marketBest.tsx
src/components/home/market/marketNew.tsx
src/components/magazine/magazineBanner/magazineBanner.tsx
src/components/magazine/magazineList/magazineList.tsx
src/hooks/queries/useHome.ts
src/hooks/queries/useMagazine.ts
src/pages/index.tsx
src/pages/magazine/index.tsx
src/utils/api/fetcher.ts
src/utils/api/magazine.ts

홈 & 매거진 페이지에 에러바운더리를 추가했습니다.
```javascript
<QueryErrorResetBoundary>
{({ reset }) => (
<>
<ErrorBoundary
onReset={reset}
fallbackRender={(props) => (
<ErrorFallback margin="100px 0" {...props} />
)}
>
<MagazineBanner />
<MagazineList page={page} />
</ErrorBoundary>
</>
)}
</QueryErrorResetBoundary>
```

feat : Magazine & Home 페이지 에러바운더리 추가

---

apps/web/src/components/layout/accountLayout.tsx
apps/web/src/components/layout/header/header.tsx
apps/web/src/components/layout/layout.tsx
apps/web/src/components/layout/navbar/navbar.tsx
apps/web/src/components/layout/navbar/navbarItem.tsx
packages/ui/components/hamburger/hamburger.tsx
packages/ui/components/hamburger/index.ts
packages/ui/components/index.ts
packages/ui/components/input/input.tsx
packages/ui/components/link/index.ts
packages/ui/components/link/link.tsx
packages/ui/form/formTextArea.tsx
packages/ui/index.tsx
packages/ui/package.json
packages/ui/styles/mediaQuery.ts
pnpm-lock.yaml

헤더 컴포넌트에 반응형 검색창과 햄버거 메뉴바를  추가하였습니다!
- #57

feat: 반응형 검색창 / 햄버거 메뉴바 추가

---

apps/web/src/components/account/accountCategory/accountCategory.tsx
apps/web/src/components/common/posting/posting.tsx
apps/web/src/components/layout/accountLayout.tsx
apps/web/src/components/layout/layout.styled.ts
apps/web/src/constants/account.ts
apps/web/src/hooks/mutations/community/useRemoveCommunityPost.ts
apps/web/src/pages/account/[sub]/index.tsx
packages/ui/components/container/container.tsx

마이페이지 작성글 삭제 기능을 구현해두었습니다.
+ 추가로 모바이 반응형도 적용해두었습니다.
#41 
#57

feat: Account 페이지 작성글 삭제 기능

---

apps/web/src/components/auth/findForm/findForm.tsx
apps/web/src/components/common/comment/comment.styled.ts
apps/web/src/components/common/posting/posting.tsx
apps/web/src/components/layout/header/header.tsx
apps/web/src/components/layout/navbar/navbar.tsx
apps/web/src/components/layout/navbar/navbarItem.tsx
apps/web/src/pages/community/[subject]/[category]/[id]/index.tsx

fix: 1차 QA 리스트업 피드백 (기타)
커뮤니티/매거진 쿼리 요청을 2번 날리는 거 수정하였습니다.
서버사이드에서 프리페칭할 때 쿼리 키를 잘못줘 캐슁을 못해 발생하는 문제였습니다.
이후엔 자잘한 스타일 수정만 진행하였습니다.
#89

fix: 1차 QA 리스트업 피드백 (기타)

---

apps/web/next.config.js
apps/web/src/components/inquiry/advertisementForm/advertisementForm.tsx
apps/web/src/components/inquiry/dealerForm/dealerForm.tsx
apps/web/src/components/inquiry/inquiryNavbar/inquiryNavbar.tsx
apps/web/src/components/inquiry/miscForm/miscForm.tsx
apps/web/src/components/inquiry/partnershipForm/partnershipForm.tsx
apps/web/src/components/inquiry/saleForm/saleForm.tsx
apps/web/src/constants/inquiry.ts
apps/web/src/middleware.ts
apps/web/src/pages/account/[sub]/index.tsx
apps/web/src/pages/inquiry/advertisement.tsx
apps/web/src/pages/inquiry/dealer.tsx
apps/web/src/pages/inquiry/index.tsx
apps/web/src/pages/inquiry/market.tsx
apps/web/src/pages/inquiry/partnership.tsx
apps/web/src/utils/api/home.ts
packages/lib/embeds/error.ts
packages/ui/form/form.styled.ts
packages/ui/form/formAgreement.tsx
packages/ui/form/formAttachment.tsx
packages/ui/form/formFiles.tsx
packages/ui/form/formImages.tsx
packages/ui/form/formRadio.tsx

큰 변경사항은 없습니다. 
모두 자잘한 스타일/에러핸들링 로직입니다.
플로우 변경은 문의페이지 진입 시 리다이렉트 처리 과정이 변했는데 모달창으로 유저에게 알리는 플로우가 추가되었습니다!
#89 
#48

fix: 1차 QA 리스트업 피드백 (문의)

---

apps/web/src/components/common/carousel/carousel.styled.ts
apps/web/src/components/common/carousel/carousel.tsx
apps/web/src/components/fallback/loading.tsx
apps/web/src/components/market/marketContents/marketContents.tsx
apps/web/src/components/partnership/partnershipCard/partnershipCard.tsx
apps/web/src/components/partnership/partnershipCategory/index.ts
apps/web/src/components/partnership/partnershipCategory/partnershipCategory.tsx
apps/web/src/components/partnership/partnershipContents/partnershipContents.tsx
apps/web/src/components/partnership/partnershipDetail/partnershipDetail.tsx
apps/web/src/components/partnership/partnershipDetailCard/partnershipDetailCard.tsx
apps/web/src/components/partnership/partnershipIntroduction/partnershipIntroduction.tsx
apps/web/src/components/partnership/partnershipList/partnershipList.tsx
apps/web/src/pages/market/[category]/[id].tsx
apps/web/src/pages/partnership/[category]/[id].tsx
apps/web/src/pages/partnership/index.tsx
apps/web/src/utils/api/partnership.ts
packages/types/partnership.d.ts
packages/ui/tsconfig.json

- 제휴업체 페이지 반응형 적용 PR 입니다.
- 변경사항
- 변경사항
- #57

feature: 제휴업체 페이지 반응형 적용

---

apps/web/src/components/partnership/partnershipDetail/partnershipDetail.tsx

- partnership comments kind=partnership으로 입력
- 변경사항
- 변경사항
-

fix(web): partnership comment kind 수정

---

apps/web/src/components/home/banner/banner.tsx
apps/web/src/components/home/banner/index.ts
apps/web/src/http/server/home/apis.ts
apps/web/src/http/server/home/keys.ts
apps/web/src/http/server/home/queries.ts
apps/web/src/pages/index.tsx

홈 배너를 구현하여 적용하였습니다.
홈에서만 쓰이는 컴포넌트/api이기 때문에,
`src/http/api/home`에 배너 훅 추가
`src/component/home/banner`에 컴포넌트를 추가하여 적용하였습니다.
#105

feat(web): 배너 적용

---

apps/web/src/components/community/communityCard/communityCard.tsx
apps/web/src/components/community/communityForm/communityForm.tsx
apps/web/src/components/magazine/magazineList/magazineList.tsx
packages/ui/components/input/input.tsx
packages/ui/form/formSelect.tsx

새롭게 2차 qa 리스트에 올라온 몇가지 버그 사항을 수정하였습니다.
스타일에 관한 변경 외엔 없습니다!
#110

fix(web,ui): 새롭게 추가된  2차 QA 리스트업 피드백 

---

apps/web/src/components/home/banner/banner.tsx
apps/web/src/components/layout/footer/footer.styled.ts
apps/web/src/components/layout/layout.styled.ts
apps/web/src/pages/_document.tsx
apps/web/src/pages/index.tsx
apps/web/src/styles/mediaQuery.ts
apps/web/src/styles/responsive.ts
packages/lib/index.ts
packages/lib/link.ts
packages/ui/styles/mediaQuery.ts
packages/ui/styles/responsive.ts

배너는 이미지 자료밖에 존재하지 않아 ssr시 검색엔진이 가져갈 자료가 없습니다.
SSR 삭제하고, 너비를 100%로 주었습니다!

feat(web): 배너 SSR 삭제 / 너비 100% 적용

---

apps/web/src/components/market/marketContents/marketContents.tsx
apps/web/src/components/market/marketDetail/components/marketLike/marketLike.tsx
apps/web/src/components/market/marketDetail/marketDetail.tsx
apps/web/src/http/server/market/apis.ts
apps/web/src/http/server/market/mutations.ts
apps/web/src/http/server/market/queries.ts
apps/web/src/pages/market/[category]/[id].tsx

- 찜하기 기능 에러 수정
- 원인: `http/server/market/apis.ts` - `getMarketPost` 내 토큰 미 전달

fix(web): 찜하기 기능 수정

---

apps/web/src/components/common/carousel/carousel.styled.ts
apps/web/src/components/common/carousel/carousel.tsx
apps/web/src/components/common/select/select.tsx
apps/web/src/components/market/marketCar/marketCar.tsx
apps/web/src/components/market/marketCard/marketCard.tsx
apps/web/src/components/market/marketDetail/components/marketDetailCarousel/marketDetailCarousel.styled.ts
apps/web/src/components/market/marketDetail/components/marketDetailCarousel/marketDetailCarousel.tsx
apps/web/src/components/market/marketFilter/marketFilterArea/marketFilterArea.tsx
apps/web/src/components/market/marketList/marketList.tsx
apps/web/src/components/market/marketRow/marketRow.tsx
apps/web/src/components/partnership/partnershipCard/partnershipCard.tsx
apps/web/src/components/partnership/partnershipDetail/partnershipDetail.tsx
apps/web/src/components/partnership/partnershipDetailCard/partnershipDetailCard.tsx
apps/web/src/hooks/useSearchKeyword.ts
packages/types/partnership.d.ts

- 모바일 QA 리스트 피드백 반영 (매물)
- #133

fix(web): 모바일 QA 리스트 피드백 반영 (매물)

---

apps/web/src/components/account/accountCategoryList/accountCategoryList.tsx
apps/web/src/components/common/posting/posting.tsx
apps/web/src/components/community/communityBestList/communityBestList.tsx
apps/web/src/components/community/communityCard/communityCard.tsx
apps/web/src/components/home/banner/banner.tsx
apps/web/src/components/home/community/community.tsx
apps/web/src/components/home/magazine/magazine.tsx
apps/web/src/components/home/market/marketBest.tsx
apps/web/src/components/home/market/marketNew.tsx
apps/web/src/components/inquiry/inquiryCard/inquiryCard.tsx
apps/web/src/http/server/home/apis.ts
apps/web/src/http/server/home/queries.ts
apps/web/src/middleware.ts
apps/web/src/pages/_app.tsx
apps/web/src/pages/account/[sub]/index.tsx
apps/web/src/pages/api/auth/[...nextauth].ts
apps/web/src/pages/index.tsx
apps/web/src/utils/misc.ts
packages/types/community.d.ts
packages/ui/components/attachedFile/attachedFile.tsx
packages/ui/components/attachedFile/index.ts
packages/ui/components/index.ts
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

구글 OAuth가 적용안되던 버그를 수정하였습니다.
kakao와 google 데이터를 전처리하는 과정에서 발생한 에러였습니다.
이외 수정은 모바일 뷰에서 레이아웃이 깨지는 문제들이였습니다.
#57 
#80

fix(web): Google OAuth 콜백 에러 / 모바일 QA 레이아웃 문제 수정

---

apps/web/src/components/account/accountCategoryList/accountCategoryList.tsx
apps/web/src/components/auth/signinForm/signinForm.tsx
apps/web/src/components/common/advertisement/index.ts
apps/web/src/components/common/advertisements/advertisements.tsx
apps/web/src/components/common/advertisements/components/advertisement.tsx
apps/web/src/components/common/advertisements/components/banner.tsx
apps/web/src/components/common/advertisements/index.ts
apps/web/src/components/home/banner/index.ts
apps/web/src/components/layout/layout.tsx
apps/web/src/http/server/home/apis.ts
apps/web/src/http/server/home/keys.ts
apps/web/src/http/server/home/queries.ts
apps/web/src/pages/api/auth/[...nextauth].ts
apps/web/src/pages/community/[subject]/[category]/[id]/index.tsx
apps/web/src/pages/community/[subject]/[category]/[id]/update.tsx
apps/web/src/pages/community/[subject]/index.tsx
apps/web/src/pages/community/create.tsx
apps/web/src/pages/index.tsx
apps/web/src/pages/inquiry/index.tsx
apps/web/src/pages/magazine/[id].tsx
apps/web/src/pages/magazine/index.tsx
apps/web/src/pages/market/[category]/[id].tsx
apps/web/src/pages/market/index.tsx
apps/web/src/pages/partnership/[category]/[id].tsx
apps/web/src/pages/partnership/index.tsx
apps/web/src/types/ads.d.ts
packages/lib/formatter.ts

광고 Api를 구현하였습니다. 
각 페이지마다 `Advertisement` 컴포넌트를 불러와서 사용하던걸 `Layout 컴포넌트` 단에서 모두 관리 할 수 있게 변경하였습니다.
#105

feat(web): 광고 Api 적용

---

apps/web/src/components/auth/signinForm/signinForm.tsx
apps/web/src/components/common/advertisements/components/advertisement.tsx
apps/web/src/components/common/comment/comment.tsx
apps/web/src/components/common/posting/posting.tsx
apps/web/src/components/inquiry/inquiryNavbar/inquiryNavbar.tsx
apps/web/src/components/magazine/magazineBanner/magazineBanner.tsx
apps/web/src/components/magazine/magazineCard/magazineCard.tsx
apps/web/src/components/magazine/magazineDealer/magazineDealer.tsx
apps/web/src/components/market/marketContents/marketContents.tsx
apps/web/src/components/partnership/partnershipContents/partnershipContents.tsx
apps/web/src/components/partnership/partnershipDetail/partnershipDetail.tsx
apps/web/src/http/server/auth/apis.ts
apps/web/src/http/server/magazine/queries.ts
apps/web/src/pages/api/auth/[...nextauth].ts
apps/web/src/pages/magazine/[id].tsx
packages/hooks/useUrlQuery.ts
packages/lib/formatter.ts
packages/ui/components/divider/divider.tsx
packages/ui/components/pagination/pagination.tsx

추가적으로 리스트 올라온 qa 리스트들을 수정하였습니다.
#110

fix(web,ui): 추가적으로 올라온 QA 리스트 피드백

---

apps/web/src/components/account/accountUpdateForm/accountUpdateForm.tsx
apps/web/src/components/auth/authFormItem/authFormItem.tsx
apps/web/src/components/auth/findIdForm/findIdForm.tsx
apps/web/src/components/auth/findPasswordForm/findPasswordForm.tsx
apps/web/src/components/auth/phoneForm/phoneForm.tsx
apps/web/src/components/auth/signupForm/signupForm.tsx
apps/web/src/components/common/advertisements/advertisements.tsx
apps/web/src/feature/DeviceProvider/deviceProvider.tsx
apps/web/src/middleware.ts

- device hints/useragent가 ssr 상황에서 undefined되는 문제로 나오는 client-side-error
- 핸드폰 인증시 인증번호 카운트가 input 창에 포커싱될때 카운팅되는 버그
- 이슈
#110

fix(web): 추가적으로 올라온 QA 리스트 피드백

---

apps/web/src/http/server/auth/apis.ts
apps/web/src/pages/api/auth/[...nextauth].ts
apps/web/src/types/next-auth.d.ts

OAuth2 플로우가 권장사항대로 흘러가지 않던 로직을 수정
1. 인가코드 발급
2. 슈퍼카 백엔드 서버로 토큰 요청 (백엔드서버에서 인가코드로 토큰/사용자 정보 처리)
3. next-auth 세션 처리
#158

refactor(web): OAuth2 플로우

---

apps/web/src/http/server/auth/apis.ts
apps/web/src/pages/api/auth/[...nextauth].ts
apps/web/src/types/next-auth.d.ts

* chore(web): oauth 토큰 서버를 슈퍼카 백엔드 서버로 이관
* refactor(web): 기존 OAuth2 플로우를 권장사항에 맞게 리팩토링

release: v1.0.1

---

apps/web/src/http/server/auth/apis.ts
apps/web/src/pages/api/auth/[...nextauth].ts

hotfix(web): OAuth Redirect Url Error

hotfix(web): OAuth Redirect Url Error

---

apps/web/src/components/account/profile/components/profileRepresentative.tsx
apps/web/src/components/community/communityCard/communityCard.tsx
apps/web/src/components/home/community/community.tsx
apps/web/src/components/home/magazine/magazine.tsx
apps/web/src/components/home/market/marketNew.tsx
apps/web/src/components/home/partnership/partnership.tsx
apps/web/src/components/home/routerButton/routerButton.tsx
apps/web/src/components/magazine/magazineCard/magazineCard.tsx
apps/web/src/constants/core.ts
apps/web/src/pages/index.tsx
packages/ui/components/searchbar/searchbar.tsx

fix(web): 새로 올라온 QA 리스트 - 1 

---

apps/web/src/components/account/profile/components/profileRepresentative.tsx
apps/web/src/components/community/communityCard/communityCard.tsx
apps/web/src/components/home/community/community.tsx
apps/web/src/components/home/magazine/magazine.tsx
apps/web/src/components/home/market/marketNew.tsx
apps/web/src/components/home/partnership/partnership.tsx
apps/web/src/components/home/routerButton/routerButton.tsx
apps/web/src/components/magazine/magazineCard/magazineCard.tsx
apps/web/src/constants/core.ts
apps/web/src/pages/index.tsx
packages/ui/components/searchbar/searchbar.tsx

* fix(web): 메인페이지 매거진 수량 버그
* fix(web): 마이페이지 갤러리 좌우 간격
* fix(web): 더보기 버튼 텍스트 웨이트
* fix(web): 검색 시 x 버튼 중복
* fix(web): 매거진 카드 flex
* fix(web): 커뮤니티 - Main - 리스트 글자
* fix(web): SEO title 변경

release(web): 전체적인 UI 관련 버그를 개선했습니다.

---

apps/web/src/components/layout/navbar/navbar.tsx
apps/web/src/components/magazine/magazineBanner/magazineBanner.tsx
apps/web/src/constants/link/navbar.ts
apps/web/src/http/server/live/apis.ts
packages/lib/text.ts

fix(web): 자잘자잘한 qa 최신 리스트 수정

---

apps/web/src/components/live/Publisher.tsx

테스트 목적으로 Dev 배포까지만 하겠습니다.
모바일 카메라 전환 테스트입니다.
- getDevice는 카메라 허용하시겠습니다 메시지가 나오지 않는다고, getUserMedia를 사용

change mobile camera device test

---

apps/web/src/components/live/Publisher.tsx
apps/web/src/components/live/Subscriber.tsx
apps/web/src/components/live/modal/Loader.tsx
apps/web/src/components/live/modal/index.tsx

Dy test rtc

---

apps/web/next.config.js
apps/web/src/components/live/ChatInfo.tsx
apps/web/src/constants/core.ts

change backend uri

---

README.md
apps/web/next.config.js
apps/web/src/components/live/ChatInfo.tsx
apps/web/src/components/live/Publisher.tsx
apps/web/src/components/live/Subscriber.tsx
apps/web/src/components/live/modal/Loader.tsx
apps/web/src/components/live/modal/index.tsx
apps/web/src/components/magazine/magazineList/magazineList.tsx
apps/web/src/constants/core.ts

- 매거진 리스트에서 첫번째는 배너 이미지이고 나머지는 본문 리스트에 넘어가도록 변경

Hot fix magazine list 첫번째값 수정

---

apps/web/src/components/common/advertisements/components/advertisement.tsx
apps/web/src/components/community/communityCard/communityCard.tsx
apps/web/src/components/magazine/magazineBanner/magazineBanner.tsx
apps/web/src/components/magazine/magazineCard/magazineCard.tsx
apps/web/src/components/search/searchAll/searchAll.tsx
apps/web/src/components/search/searchPartnership/searchPartnership.tsx
apps/web/src/http/server/home/queries.ts
apps/web/src/types/ads.d.ts
apps/web/src/types/community.d.ts
packages/lib/formatter.ts
packages/lib/text.ts

fix(web): 최종 qa 리스트업 수정

---

apps/web/src/components/auth/findIdForm/findIdForm.tsx
apps/web/src/components/common/comment/components/commentBody.tsx
apps/web/src/components/layout/footer/footer.styled.ts
apps/web/src/components/layout/footer/footer.tsx
apps/web/src/components/layout/layout.tsx
apps/web/src/components/market/marketDetail/components/marketMine/marketMine.tsx

1. 커뮤니티 게시글 댓글 좋아요 취소 기능 동작 X
2. 매물 상세에서 판매 완료 버튼 클릭 시 완료가 됐으나 그 이후 동작 없음
3. 아이디 찾기 후 회원가입 시 인증번호
4. 이용약관 및 개인정보처리방침 추가

fix: 최종 qa 리스트 수정

---

apps/web/src/components/magazine/magazineList/magazineList.tsx

1. 매거진 메뉴에서 "따근따근 최신 소식" 영역을 클릭 시 상세 조회 할 수 있도록 변경했습니다.

fix. 매거진 따끈따끈한 최식소식의 매거진 클릭 시 상세 페이지 Link 추가

---

apps/web/package.json
apps/web/src/components/account/accountCategoryList/accountCategoryList.tsx
apps/web/src/components/market/marketContents/marketContents.tsx
apps/web/src/components/market/marketDetail/components/marketDetailCarousel/marketDetailCarousel.tsx
apps/web/src/components/market/marketDetail/components/marketMine/marketMine.tsx
apps/web/src/http/server/market/apis.ts
apps/web/src/http/server/market/mutations.ts
pnpm-lock.yaml

* feat: 매물 워터마크 추가
* fix: 마이페이지 판매 완료버튼 완료 이후 동작 X

release(web): v1.0.6
